const KOREAN_CITY_ALIASES = {
  서울: "Seoul,KR",
  서울시: "Seoul,KR",
  서울특별시: "Seoul,KR",
  부산: "Busan,KR",
  부산시: "Busan,KR",
  부산광역시: "Busan,KR",
  대구: "Daegu,KR",
  대구시: "Daegu,KR",
  대구광역시: "Daegu,KR",
  인천: "Incheon,KR",
  인천시: "Incheon,KR",
  인천광역시: "Incheon,KR",
  광주: "Gwangju,KR",
  광주시: "Gwangju,KR",
  광주광역시: "Gwangju,KR",
  대전: "Daejeon,KR",
  대전시: "Daejeon,KR",
  대전광역시: "Daejeon,KR",
  울산: "Ulsan,KR",
  울산시: "Ulsan,KR",
  울산광역시: "Ulsan,KR",
  세종: "Sejong,KR",
  세종시: "Sejong,KR",
  제주: "Jeju,KR",
  제주시: "Jeju,KR",
  수원: "Suwon,KR",
  성남: "Seongnam,KR",
  고양: "Goyang,KR",
  용인: "Yongin,KR",
  창원: "Changwon,KR",
  청주: "Cheongju,KR",
  전주: "Jeonju,KR",
  천안: "Cheonan,KR",
  포항: "Pohang,KR",
  김해: "Gimhae,KR",
  평택: "Pyeongtaek,KR",
  안산: "Ansan,KR",
  안양: "Anyang,KR",
  부천: "Bucheon,KR",
  남양주: "Namyangju,KR",
  화성: "Hwaseong,KR",
  원주: "Wonju,KR",
  춘천: "Chuncheon,KR",
  강릉: "Gangneung,KR",
  여수: "Yeosu,KR",
  목포: "Mokpo,KR",
  순천: "Suncheon,KR",
  경주: "Gyeongju,KR",
  구미: "Gumi,KR",
  진주: "Jinju,KR",
  통영: "Tongyeong,KR",
  거제: "Geoje,KR",
};

const COUNTRY_REPRESENTATIVE_QUERIES = {
  AD: "Andorra la Vella,AD",
  AE: "Abu Dhabi,AE",
  AF: "Kabul,AF",
  AG: "Saint John's,AG",
  AI: "The Valley,AI",
  AL: "Tirana,AL",
  AM: "Yerevan,AM",
  AO: "Luanda,AO",
  AR: "Buenos Aires,AR",
  AS: "Pago Pago,AS",
  AT: "Vienna,AT",
  AU: "Canberra,AU",
  AW: "Oranjestad,AW",
  AX: "Mariehamn,AX",
  AZ: "Baku,AZ",
  BA: "Sarajevo,BA",
  BB: "Bridgetown,BB",
  BD: "Dhaka,BD",
  BE: "Brussels,BE",
  BF: "Ouagadougou,BF",
  BG: "Sofia,BG",
  BH: "Manama,BH",
  BI: "Bujumbura,BI",
  BJ: "Porto-Novo,BJ",
  BL: "Gustavia,BL",
  BM: "Hamilton,BM",
  BN: "Bandar Seri Begawan,BN",
  BO: "La Paz,BO",
  BQ: "Kralendijk,BQ",
  BR: "Brasilia,BR",
  BS: "Nassau,BS",
  BT: "Thimphu,BT",
  BW: "Gaborone,BW",
  BY: "Minsk,BY",
  BZ: "Belmopan,BZ",
  CA: "Ottawa,CA",
  CC: "West Island,CC",
  CD: "Kinshasa,CD",
  CF: "Bangui,CF",
  CG: "Brazzaville,CG",
  CH: "Bern,CH",
  CI: "Yamoussoukro,CI",
  CK: "Avarua,CK",
  CL: "Santiago,CL",
  CM: "Yaounde,CM",
  CN: "Beijing,CN",
  CO: "Bogota,CO",
  CR: "San Jose,CR",
  CU: "Havana,CU",
  CV: "Praia,CV",
  CW: "Willemstad,CW",
  CX: "Flying Fish Cove,CX",
  CY: "Nicosia,CY",
  CZ: "Prague,CZ",
  DE: "Berlin,DE",
  DJ: "Djibouti,DJ",
  DK: "Copenhagen,DK",
  DM: "Roseau,DM",
  DO: "Santo Domingo,DO",
  DZ: "Algiers,DZ",
  EC: "Quito,EC",
  EE: "Tallinn,EE",
  EG: "Cairo,EG",
  ER: "Asmara,ER",
  ES: "Madrid,ES",
  ET: "Addis Ababa,ET",
  FI: "Helsinki,FI",
  FJ: "Suva,FJ",
  FK: "Stanley,FK",
  FM: "Palikir,FM",
  FO: "Torshavn,FO",
  FR: "Paris,FR",
  GA: "Libreville,GA",
  GB: "London,GB",
  GD: "Saint George's,GD",
  GE: "Tbilisi,GE",
  GF: "Cayenne,GF",
  GG: "Saint Peter Port,GG",
  GH: "Accra,GH",
  GI: "Gibraltar,GI",
  GL: "Nuuk,GL",
  GM: "Banjul,GM",
  GN: "Conakry,GN",
  GP: "Basse-Terre,GP",
  GQ: "Malabo,GQ",
  GR: "Athens,GR",
  GT: "Guatemala City,GT",
  GU: "Hagatna,GU",
  GW: "Bissau,GW",
  GY: "Georgetown,GY",
  HK: "Hong Kong,HK",
  HN: "Tegucigalpa,HN",
  HR: "Zagreb,HR",
  HT: "Port-au-Prince,HT",
  HU: "Budapest,HU",
  ID: "Jakarta,ID",
  IE: "Dublin,IE",
  IL: "Jerusalem,IL",
  IM: "Douglas,IM",
  IN: "New Delhi,IN",
  IO: "Diego Garcia,IO",
  IQ: "Baghdad,IQ",
  IR: "Tehran,IR",
  IS: "Reykjavik,IS",
  IT: "Rome,IT",
  JE: "Saint Helier,JE",
  JM: "Kingston,JM",
  JO: "Amman,JO",
  JP: "Tokyo,JP",
  KE: "Nairobi,KE",
  KG: "Bishkek,KG",
  KH: "Phnom Penh,KH",
  KI: "Tarawa,KI",
  KM: "Moroni,KM",
  KN: "Basseterre,KN",
  KP: "Pyongyang,KP",
  KR: "Seoul,KR",
  KW: "Kuwait City,KW",
  KY: "George Town,KY",
  KZ: "Astana,KZ",
  LA: "Vientiane,LA",
  LB: "Beirut,LB",
  LC: "Castries,LC",
  LI: "Vaduz,LI",
  LK: "Colombo,LK",
  LR: "Monrovia,LR",
  LS: "Maseru,LS",
  LT: "Vilnius,LT",
  LU: "Luxembourg,LU",
  LV: "Riga,LV",
  LY: "Tripoli,LY",
  MA: "Rabat,MA",
  MC: "Monaco,MC",
  MD: "Chisinau,MD",
  ME: "Podgorica,ME",
  MF: "Marigot,MF",
  MG: "Antananarivo,MG",
  MH: "Majuro,MH",
  MK: "Skopje,MK",
  ML: "Bamako,ML",
  MM: "Naypyidaw,MM",
  MN: "Ulaanbaatar,MN",
  MO: "Macau,MO",
  MP: "Saipan,MP",
  MQ: "Fort-de-France,MQ",
  MR: "Nouakchott,MR",
  MS: "Plymouth,MS",
  MT: "Valletta,MT",
  MU: "Port Louis,MU",
  MV: "Male,MV",
  MW: "Lilongwe,MW",
  MX: "Mexico City,MX",
  MY: "Kuala Lumpur,MY",
  MZ: "Maputo,MZ",
  NA: "Windhoek,NA",
  NC: "Noumea,NC",
  NE: "Niamey,NE",
  NF: "Kingston,NF",
  NG: "Abuja,NG",
  NI: "Managua,NI",
  NL: "Amsterdam,NL",
  NO: "Oslo,NO",
  NP: "Kathmandu,NP",
  NR: "Yaren,NR",
  NU: "Alofi,NU",
  NZ: "Wellington,NZ",
  OM: "Muscat,OM",
  PA: "Panama City,PA",
  PE: "Lima,PE",
  PF: "Papeete,PF",
  PG: "Port Moresby,PG",
  PH: "Manila,PH",
  PK: "Islamabad,PK",
  PL: "Warsaw,PL",
  PM: "Saint-Pierre,PM",
  PN: "Adamstown,PN",
  PR: "San Juan,PR",
  PS: "Ramallah,PS",
  PT: "Lisbon,PT",
  PW: "Koror,PW",
  PY: "Asuncion,PY",
  QA: "Doha,QA",
  RE: "Saint-Denis,RE",
  RO: "Bucharest,RO",
  RS: "Belgrade,RS",
  RU: "Moscow,RU",
  RW: "Kigali,RW",
  SA: "Riyadh,SA",
  SB: "Honiara,SB",
  SC: "Victoria,SC",
  SD: "Khartoum,SD",
  SE: "Stockholm,SE",
  SG: "Singapore,SG",
  SH: "Jamestown,SH",
  SI: "Ljubljana,SI",
  SK: "Bratislava,SK",
  SL: "Freetown,SL",
  SM: "San Marino,SM",
  SN: "Dakar,SN",
  SO: "Mogadishu,SO",
  SR: "Paramaribo,SR",
  SS: "Juba,SS",
  ST: "Sao Tome,ST",
  SV: "San Salvador,SV",
  SX: "Philipsburg,SX",
  SY: "Damascus,SY",
  SZ: "Mbabane,SZ",
  TC: "Cockburn Town,TC",
  TD: "N'Djamena,TD",
  TG: "Lome,TG",
  TH: "Bangkok,TH",
  TJ: "Dushanbe,TJ",
  TK: "Fakaofo,TK",
  TL: "Dili,TL",
  TM: "Ashgabat,TM",
  TN: "Tunis,TN",
  TO: "Nuku'alofa,TO",
  TR: "Ankara,TR",
  TT: "Port of Spain,TT",
  TV: "Funafuti,TV",
  TW: "Taipei,TW",
  TZ: "Dodoma,TZ",
  UA: "Kyiv,UA",
  UG: "Kampala,UG",
  US: "Washington,US",
  UY: "Montevideo,UY",
  UZ: "Tashkent,UZ",
  VA: "Vatican City,VA",
  VC: "Kingstown,VC",
  VE: "Caracas,VE",
  VG: "Road Town,VG",
  VI: "Charlotte Amalie,VI",
  VN: "Hanoi,VN",
  VU: "Port Vila,VU",
  WF: "Mata-Utu,WF",
  WS: "Apia,WS",
  XK: "Pristina,XK",
  YE: "Sanaa,YE",
  YT: "Mamoudzou,YT",
  ZA: "Pretoria,ZA",
  ZM: "Lusaka,ZM",
  ZW: "Harare,ZW",
};

const KOREAN_COUNTRY_ALIASES = buildKoreanCountryAliases();

const MANUAL_LOCATION_ALIASES = {
  한국: "Seoul,KR",
  대한민국: "Seoul,KR",
  남한: "Seoul,KR",
  북한: "Pyongyang,KP",
  미국: "Washington,US",
  영국: "London,GB",
  잉글랜드: "London,GB",
  스코틀랜드: "Edinburgh,GB",
  웨일스: "Cardiff,GB",
  북아일랜드: "Belfast,GB",
  중국: "Beijing,CN",
  일본: "Tokyo,JP",
  대만: "Taipei,TW",
  홍콩: "Hong Kong,HK",
  마카오: "Macau,MO",
  러시아: "Moscow,RU",
  튀르키예: "Ankara,TR",
  터키: "Ankara,TR",
  체코: "Prague,CZ",
  베트남: "Hanoi,VN",
  태국: "Bangkok,TH",
  필리핀: "Manila,PH",
  인도네시아: "Jakarta,ID",
  말레이시아: "Kuala Lumpur,MY",
  싱가포르: "Singapore,SG",
  인도: "New Delhi,IN",
  호주: "Canberra,AU",
  뉴질랜드: "Wellington,NZ",
  캐나다: "Ottawa,CA",
  멕시코: "Mexico City,MX",
  브라질: "Brasilia,BR",
  아르헨티나: "Buenos Aires,AR",
  프랑스: "Paris,FR",
  독일: "Berlin,DE",
  이탈리아: "Rome,IT",
  스페인: "Madrid,ES",
  포르투갈: "Lisbon,PT",
  네덜란드: "Amsterdam,NL",
  스위스: "Bern,CH",
  오스트리아: "Vienna,AT",
  스웨덴: "Stockholm,SE",
  노르웨이: "Oslo,NO",
  핀란드: "Helsinki,FI",
  덴마크: "Copenhagen,DK",
  아이슬란드: "Reykjavik,IS",
  사우디: "Riyadh,SA",
  사우디아라비아: "Riyadh,SA",
  아랍에미리트: "Abu Dhabi,AE",
  두바이: "Dubai,AE",
  카타르: "Doha,QA",
  이스라엘: "Jerusalem,IL",
  이집트: "Cairo,EG",
  남아공: "Pretoria,ZA",
  남아프리카공화국: "Pretoria,ZA",
};

const LOCATION_ALIASES = {
  ...KOREAN_COUNTRY_ALIASES,
  ...KOREAN_CITY_ALIASES,
  ...MANUAL_LOCATION_ALIASES,
};

function buildKoreanCountryAliases() {
  const regionNames = new Intl.DisplayNames(["ko"], { type: "region" });

  return Object.fromEntries(
    Object.entries(COUNTRY_REPRESENTATIVE_QUERIES)
      .map(([countryCode, query]) => [compactLocation(regionNames.of(countryCode)), query])
      .filter(([name]) => Boolean(name)),
  );
}

function compactLocation(value) {
  return value.replace(/\s+/g, "").toLowerCase();
}

export function normalizeLocationQuery(location) {
  const compactLocationName = compactLocation(location);

  return LOCATION_ALIASES[compactLocationName] || location;
}
